import { useEffect, useState } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { ShieldCheck, ExternalLink, AlertTriangle } from 'lucide-react';
import { useAuth } from '../lib/AuthContext';
import {
  savePendingConnect,
  loadPendingConnect,
  clearPendingConnect,
  isSafeReturnUrl,
  type PendingConnect,
} from '../lib/pendingConnect';

/**
 * Third-party connect handshake.
 *
 * Flow: WordPress plugin (or Make.com, browser extension, Telegram bot)
 * sends the user here with `return_url`, `state`, and `app` query params.
 * ProtectedRoute forces a login first if needed. Once authenticated, the
 * user sees exactly which app is asking and what it gets, and can approve
 * or cancel. On approve we redirect to `${return_url}?api_key=...&state=...`.
 *
 * `state` is opaque to us — it's generated by the requesting app and
 * echoed back so *it* can verify the response wasn't forged/replayed.
 */
export default function Connect() {
  const [searchParams] = useSearchParams();
  const { profile } = useAuth();
  const [pending, setPending] = useState<PendingConnect | null>(null);
  const [invalid, setInvalid] = useState(false);
  const [redirecting, setRedirecting] = useState(false);

  useEffect(() => {
    const returnUrl = searchParams.get('return_url');
    const state = searchParams.get('state');
    const app = searchParams.get('app') || 'A third-party app';

    if (returnUrl && state) {
      if (!isSafeReturnUrl(returnUrl)) {
        setInvalid(true);
        return;
      }
      const p = { returnUrl, state, app };
      savePendingConnect(p);
      setPending(p);
      return;
    }

    // No query params — likely bounced back here after login/signup or
    // email confirmation. Recover whatever was stashed before that detour.
    const stored = loadPendingConnect();
    if (stored) {
      setPending(stored);
    } else {
      setInvalid(true);
    }
  }, [searchParams]);

  const handleApprove = () => {
    if (!pending || !profile) return;
    setRedirecting(true);
    const url = new URL(pending.returnUrl);
    url.searchParams.set('api_key', profile.api_key);
    url.searchParams.set('state', pending.state);
    clearPendingConnect();
    window.location.href = url.toString();
  };

  const handleCancel = () => {
    clearPendingConnect();
    setPending(null);
    setInvalid(true);
  };

  return (
    <div className="min-h-screen bg-black text-white flex items-center justify-center px-4">
      <div className="w-full max-w-md liquid-glass rounded-2xl p-8">
        {invalid || !pending ? (
          <>
            <AlertTriangle className="w-8 h-8 text-yellow-400 mb-4" />
            <h1 className="text-xl font-semibold mb-2">Nothing to connect</h1>
            <p className="text-sm text-gray-400 mb-6">
              This link is missing or invalid connection details. Go back to the app you were
              setting up and try connecting again.
            </p>
            <Link to="/dashboard" className="text-sm text-white underline underline-offset-4">
              Go to dashboard
            </Link>
          </>
        ) : (
          <>
            <ShieldCheck className="w-8 h-8 text-emerald-400 mb-4" />
            <h1 className="text-xl font-semibold mb-2">Connect {pending.app}</h1>
            <p className="text-sm text-gray-400 mb-6">
              <strong className="text-white">{pending.app}</strong> wants to use your Visora API
              key to render images on your behalf. This lets it call the Visora render API as
              you — it does not grant access to your account, billing, or dashboard.
            </p>

            <div className="bg-black/40 border border-white/10 rounded-lg px-4 py-3 mb-6 text-xs text-gray-400 flex items-center gap-2">
              <code className="font-mono truncate">{profile?.api_key}</code>
            </div>

            <div className="flex gap-3">
              <button
                onClick={handleApprove}
                disabled={redirecting}
                className="flex-1 bg-white text-black rounded-full font-medium py-2.5 hover:bg-gray-200 transition-colors disabled:opacity-60 cursor-pointer flex items-center justify-center gap-2"
              >
                {redirecting ? 'Redirecting…' : 'Allow & return'}
                {!redirecting && <ExternalLink className="w-4 h-4" />}
              </button>
              <button
                onClick={handleCancel}
                disabled={redirecting}
                className="rounded-full liquid-glass font-medium py-2.5 px-6 hover:bg-white/10 transition-colors disabled:opacity-60 cursor-pointer"
              >
                Cancel
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
