name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # Или master, в зависимости от имени вашей основной ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Если используются npm-зависимости, раскомментируйте следующие шаги:
      # - name: Install dependencies
      #   run: npm ci

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # Раскомментируйте, если требуется ID аккаунта
